/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */

/*
odd even odd odd even odd odd even odd odd even
                   fn-6            fn-3        fn
fn = fn-1+fn-2
fn-2+fn-3 + fn-3 +fn-4
2fn-3 + fn-3+fn-4+fn-5+fn-6
4fn-3+fn-6
n=0 2
n=1 8
n   4fn-3+fn-6

 */
public class P2 {
    public static void main(String[] args) {
        int limit = 4000000;
        int a=2;
        int b=8;
        int sum = a+b;
        int temp;
        do{
            temp = 4*b + a;
            if(temp < limit){
                sum+=temp;
            }
            a=b;
            b=temp;

        }while(b<limit);
            System.out.print(sum);
    }

}
